In [2]:
import numpy as np
import pandas as pd

/usr/lib/python3/dist-packages/pytz/__init__.py:31: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  match = re.match("^#\s*version\s*([0-9a-z]*)\s*$", line)

In [3]:
df=pd.read_csv("data.csv", encoding="latin1")
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55     17850.0  United Kingdom
1        12/1/2010 8:26       3.39     17850.0  United Kingdom
2        12/1/2010 8:26       2.75     17850.0  United Kingdom
3        12/1/2010 8:26       3.39     17850.0  United Kingdom
4        12/1/2010 8:26       3.39     17850.0  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85     12680.0          France
541905  12/9/2011 12:50       2.10     12680.0          France
541906  12/9/2011 12:50       4.15     12680.0          France
541907  12/9/2011 12:50       4.15     12680.0          France
541908  12/9/2011 12:50       4.95     12680.0          France

[541909 rows x 8 columns]

In [4]:
print("Data load successful: \n")

Data load successful:

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [6]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [7]:
print("shape (rows,cols:)", df.shape)

shape (rows,cols:) (541909, 8)

In [8]:
df.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country']

## Step 2- Basic Exploration

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [10]:
print("Col- missing nulls: \n", df.isnull().sum())

Col- missing nulls:
 InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [11]:
df.duplicated().count()

np.int64(541909)

In [12]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

## Step 3 - Data Cleaning

In [13]:
df=df.dropna(subset=["Description"])

In [14]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133626
Country             0
dtype: int64

In [15]:
df_cust=df.dropna(subset=["CustomerID"]).copy()
df_cust["CustomerID"]=df_cust["CustomerID"].astype(int)
print(df_cust)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55       17850  United Kingdom
1        12/1/2010 8:26       3.39       17850  United Kingdom
2        12/1/2010 8:26       2.75       17850  United Kingdom
3        12/1/2010 8:26       3.39       17850  United Kingdom
4        12/1/2010 8:26       3.39       17850  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85       12680          France
541905  12/9/2011 12:50       2.10       12680          France
541906  12/9/2011 12:50       4.15       12680          France
541907  12/9/2011 12:50       4.15       12680          France
541908  12/9/2011 12:50       4.95       12680          France

[406829 rows x 8 columns]

In [16]:
df["IsCancelled"]=df["InvoiceNo"].astype(str).str.startswith("c").sum()

In [17]:
df["IsCancelled"]

0         0
1         0
2         0
3         0
4         0
         ..
541904    0
541905    0
541906    0
541907    0
541908    0
Name: IsCancelled, Length: 540455, dtype: int64

In [18]:
df_clean=df[(~df["IsCancelled"]) & #rows where IsCancelled is False
            (df["Quantity"]>0) & #keep and check quantity is greater than 0
            (df["UnitPrice"]>0) #keep only and check rows UnitPrice is greater than 0
            ].copy() #seperate copy of filtered df

In [19]:
df_clean["InvoiceDate"]=pd.to_datetime(df_clean["InvoiceDate"],format="%m/%d/%Y %H:%M")

In [20]:
df_clean["InvoiceDate"]

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 530104, dtype: datetime64[us]

In [21]:
df_clean["TotalPrice"]=np.multiply(df_clean["Quantity"], df_clean["UnitPrice"])

In [22]:
print("STEP 3: Data Cleaned")
print("Original rows: ", df.shape[0], "| Clean rows:", df_clean.shape[0])
print("Cancelled orders removed: ", df["IsCancelled"].sum())
print(df_clean[["InvoiceNo", "Quantity", "UnitPrice", "TotalPrice", "InvoiceDate"]].head())
print("\n")

STEP 3: Data Cleaned
Original rows:  540455 | Clean rows: 530104
Cancelled orders removed:  0
  InvoiceNo  Quantity  UnitPrice  TotalPrice         InvoiceDate
0    536365         6       2.55       15.30 2010-12-01 08:26:00
1    536365         6       3.39       20.34 2010-12-01 08:26:00
2    536365         8       2.75       22.00 2010-12-01 08:26:00
3    536365         6       3.39       20.34 2010-12-01 08:26:00
4    536365         6       3.39       20.34 2010-12-01 08:26:00

## Step 4 - Date Based Features (for time analysis)

In [23]:
df_clean["Year"]=df_clean["InvoiceDate"].dt.year
df_clean["Month"]=df_clean["InvoiceDate"].dt.month
df_clean["Day"]=df_clean["InvoiceDate"].dt.day
df_clean["Hour"]=df_clean["InvoiceDate"].dt.hour
df_clean["DayOfWeek"]=df_clean["InvoiceDate"].dt.day_name()

In [24]:
print("Step 4- Date features added")
print(df_clean[["InvoiceDate","Year","Month","DayOfWeek","Hour"]].head(10))
print("\n")

Step 4- Date features added
          InvoiceDate  Year  Month  DayOfWeek  Hour
0 2010-12-01 08:26:00  2010     12  Wednesday     8
1 2010-12-01 08:26:00  2010     12  Wednesday     8
2 2010-12-01 08:26:00  2010     12  Wednesday     8
3 2010-12-01 08:26:00  2010     12  Wednesday     8
4 2010-12-01 08:26:00  2010     12  Wednesday     8
5 2010-12-01 08:26:00  2010     12  Wednesday     8
6 2010-12-01 08:26:00  2010     12  Wednesday     8
7 2010-12-01 08:28:00  2010     12  Wednesday     8
8 2010-12-01 08:28:00  2010     12  Wednesday     8
9 2010-12-01 08:34:00  2010     12  Wednesday     8

## Step 5- Key Business Metrices

In [28]:
total_rev=np.sum(df_clean["TotalPrice"])
total_orders=df_clean["InvoiceNo"].nunique()
total_cust=df_clean["CustomerID"].nunique()
avg_order_value=df_clean.groupby("InvoiceNo")["TotalPrice"].sum().mean()

In [29]:
print("Step 5- Key Metrices")
print(f"Total Revenue: {total_rev:,.2f}")
print(f"Total Orders: {total_orders}")
print(f"Total Customers: {total_cust}")
print(f"Total Order Value: {avg_order_value:,.2f}")

Step 5- Key Metrices
Total Revenue: 10,666,684.54
Total Orders: 19960
Total Customers: 4338
Total Order Value: 534.40

## Step 6- Top 10 Prodcuts

In [30]:
top_prdcts_rev=(
    df_clean.groupby("Description")["TotalPrice"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_prdcts_qty=(
    df_clean.groupby("Description")["Quantity"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

In [31]:
print(top_prdcts_qty)
print(top_prdcts_rev)

Description
PAPER CRAFT , LITTLE BIRDIE           80995
MEDIUM CERAMIC TOP STORAGE JAR        78033
WORLD WAR 2 GLIDERS ASSTD DESIGNS     55047
JUMBO BAG RED RETROSPOT               48474
WHITE HANGING HEART T-LIGHT HOLDER    37891
POPCORN HOLDER                        36761
ASSORTED COLOUR BIRD ORNAMENT         36461
PACK OF 72 RETROSPOT CAKE CASES       36419
RABBIT NIGHT LIGHT                    30788
MINI PAINT SET VINTAGE                26633
Name: Quantity, dtype: int64
Description
DOTCOM POSTAGE                        206248.77
REGENCY CAKESTAND 3 TIER              174484.74
PAPER CRAFT , LITTLE BIRDIE           168469.60
WHITE HANGING HEART T-LIGHT HOLDER    106292.77
PARTY BUNTING                          99504.33
JUMBO BAG RED RETROSPOT                94340.05
MEDIUM CERAMIC TOP STORAGE JAR         81700.92
Manual                                 78112.82
POSTAGE                                78101.88
RABBIT NIGHT LIGHT                     66964.99
Name: TotalPrice, dtype: float64

## Step 7- Country Wise Analysis

In [32]:
country_rev=(
    df_clean.groupby("Country")["TotalPrice"]
    .sum()
    .sort_values(ascending=False)
)

In [34]:
print(country_rev.astype(int))

Country
United Kingdom          9025222
Netherlands              285446
EIRE                     283453
Germany                  228867
France                   209715
Australia                138521
Spain                     61577
Switzerland               57089
Belgium                   41196
Sweden                    38378
Japan                     37416
Norway                    36165
Portugal                  33747
Finland                   22546
Singapore                 21279
Channel Islands           20450
Denmark                   18955
Italy                     17483
Hong Kong                 15691
Cyprus                    13590
Austria                   10198
Israel                     8135
Poland                     7334
Greece                     4760
Unspecified                4749
Iceland                    4310
Canada                     3666
USA                        3580
Malta                      2725
United Arab Emirates       1902
Lebanon                    1693
Lithuania                  1661
European Community         1300
Brazil                     1143
RSA                        1002
Czech Republic              826
Bahrain                     754
Saudi Arabia                145
Name: TotalPrice, dtype: int64

## Step 8- Monthly Sales trend

In [35]:
df_clean["YearMonth"]=df_clean["InvoiceDate"].dt.to_period("M")
monthly_sales=df_clean.groupby("YearMonth")["TotalPrice"].sum()

In [36]:
print(monthly_sales)

YearMonth
2010-12     823746.140
2011-01     691364.560
2011-02     523631.890
2011-03     717639.360
2011-04     537808.621
2011-05     770536.020
2011-06     761739.900
2011-07     719221.191
2011-08     759138.380
2011-09    1058590.172
2011-10    1154979.300
2011-11    1509496.330
2011-12     638792.680
Freq: M, Name: TotalPrice, dtype: float64

## Step 9- Top 10 Customers (Customer Analysis- RFM style)

In [37]:
cust_summary= df_clean.groupby("CustomerID").agg(
    TotalSpent=("TotalPrice","sum"),
    NumOrders=("InvoiceNo","nunique"),
    AvgOrderValue=("TotalPrice","mean"),
    LastPurchase=("InvoiceDate","max")
).sort_values("TotalSpent",ascending=False)

In [39]:
print(cust_summary.head(5))

            TotalSpent  NumOrders  AvgOrderValue        LastPurchase
CustomerID
14646.0      280206.02         73     134.973998 2011-12-08 12:12:00
18102.0      259657.30         60     602.453132 2011-12-09 11:50:00
17450.0      194550.79         46     577.302047 2011-12-01 13:29:00
16446.0      168472.50          2   56157.500000 2011-12-09 09:15:00
14911.0      143825.06        201      25.343623 2011-12-08 15:54:00

## Step 10- Numpy based staticstical analysis

In [41]:
order_value= df_clean.groupby("InvoiceNo")["TotalPrice"].sum()

In [42]:
order_value

InvoiceNo
536365       139.12
536366        22.20
536367       278.73
536368        70.05
536369        17.85
             ...
581584       140.64
581585       329.05
581586       339.20
581587       249.45
A563185    11062.06
Name: TotalPrice, Length: 19960, dtype: float64

In [43]:
print("Mean:", np.mean(order_value))
print("Median:", np.median(order_value))
print("Standard Deviation:", np.std(order_value))
print("Max:", np.max(order_value))
print("Min:", np.min(order_value))
print("25th Percentile:", np.percentile(order_value,25))
print("75th Percentile:", np.percentile(order_value,75))
print()

Mean: 534.403033266533
Median: 303.83500000000004
Standard Deviation: 1780.4430456461234
Max: 168469.6
Min: 0.38
25th Percentile: 152.51
75th Percentile: 495.615

## Step 11- Save Cleaned data and summary outputs

In [44]:
df_clean.to_csv("cleaned_ecommerce_data.csv", index=False)
cust_summary.to_csv("cust_summary.csv")
country_rev.to_csv("country_rev.csv")